require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    # bundled gems
    - vendor/**/*
    # testing gems
    - testing/vendor/**/*

Layout/LineLength:
  Max: 100

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false